"""Macro recording and playback system.

Aligns with Photoshop Actions / Blender macro philosophy: records a
sequence of user operations and generates a reusable Python script.
"""
from pathlib import Path
from typing import Any, Dict, List


class MacroStep:
    """A single step in a recorded macro."""

    def __init__(
        self,
        operator_name: str,
        config: Dict[str, Any],
        description: str = "",
    ) -> None:
        self.operator_name = operator_name
        self.config = config
        self.description = description


class MacroRecorder:
    """Records a sequence of operations and generates a replayable script.

    Usage:
        recorder = MacroRecorder()
        recorder.start()
        recorder.record("grid_splitter", {"rows": 3, "cols": 3})
        recorder.record("resizer", {"width": 0.5, "height": 0.5})
        script_text = recorder.stop()
        # script_text can be saved to file and replayed via ScriptEngine
    """

    def __init__(self) -> None:
        self._recording: bool = False
        self._steps: List[MacroStep] = []

    @property
    def is_recording(self) -> bool:
        """Check if the recorder is actively recording."""
        return self._recording

    @property
    def step_count(self) -> int:
        """Number of recorded steps."""
        return len(self._steps)

    def start(self) -> None:
        """Begin recording a new macro. Clears any previous recording."""
        self._steps.clear()
        self._recording = True

    def stop(self) -> str:
        """Stop recording and return the generated script as a string.

        Returns:
            A Python script string that can be saved and replayed.
            Returns an empty string if no steps were recorded.
        """
        self._recording = False
        return self._generate_script()

    def cancel(self) -> None:
        """Cancel recording without generating a script."""
        self._recording = False
        self._steps.clear()

    def record(
        self,
        operator_name: str,
        config: Dict[str, Any],
        description: str = "",
    ) -> None:
        """Record a single operation step.

        Args:
            operator_name: Name of the operator (processor).
            config: Configuration dictionary used for the operation.
            description: Optional human-readable description.

        Raises:
            RuntimeError: If the recorder is not in recording mode.
        """
        if not self._recording:
            raise RuntimeError("MacroRecorder is not recording. Call start() first.")
        self._steps.append(MacroStep(operator_name, config, description))

    def _generate_script(self) -> str:
        """Generate a replayable Python script from recorded steps."""
        if not self._steps:
            return ""

        lines = [
            "# Auto-generated macro script",
            "# Generated by Image Splitter Pro macro recorder",
            "",
            "from image_splitter.script_engine import ScriptEngine",
            "",
            "def run_macro(input_files, output_dir='./output'):",
            '    """Execute recorded macro."""',
            "    engine = ScriptEngine()",
        ]

        for i, step in enumerate(self._steps, 1):
            config_repr = self._format_config(step.config)
            lines.append(f"    # Step {i}: {step.operator_name}")
            if step.description:
                lines.append(f"    #   {step.description}")
            lines.append(
                f"    result_{i} = engine.process("
                f"input_files, '{step.operator_name}', {config_repr}"
                f")"
            )
            lines.append(
                f"    if not result_{i}.success:"
            )
            lines.append(
                f"        return result_{i}"
            )

        lines.append("    return result_" + str(len(self._steps)))
        lines.append("")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    import sys")
        lines.append("    if len(sys.argv) < 2:")
        lines.append('        print("Usage: python macro.py <input_file> [output_dir]")')
        lines.append("        sys.exit(1)")
        lines.append("    output_dir = sys.argv[2] if len(sys.argv) > 2 else './output'")
        lines.append("    result = run_macro([sys.argv[1]], output_dir)")
        lines.append("    print(result.message)")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _format_config(config: Dict[str, Any]) -> str:
        """Format a config dict as a Python literal string.

        Uses repr() for values to ensure safe embedding in generated Python code.
        Path strings are normalized to forward slashes to avoid escape issues.
        """
        items = []
        for key, value in config.items():
            if isinstance(value, str):
                safe_value = value.replace("\\", "/")
                items.append(f"'{key}': {safe_value!r}")
            else:
                items.append(f"'{key}': {value!r}")
        return "{" + ", ".join(items) + "}"

    def save(self, output_path: str) -> bool:
        """Stop recording and save the generated script to a file.

        Args:
            output_path: Path to save the script file.

        Returns:
            True if a script was saved, False if no steps were recorded.
        """
        script = self.stop()
        if not script:
            return False
        out_path = Path(output_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(script)
        return True


class MacroPlayer:
    """Plays back a recorded macro script."""

    @staticmethod
    def play(
        script_path: str,
        input_files: List[str],
        output_dir: str = "./output",
    ) -> Any:
        """Execute a macro script file.

        The script file should contain a ``run_macro(input_files, output_dir)``
        function that uses ScriptEngine to process files.

        Args:
            script_path: Path to the macro Python script file.
            input_files: List of input image paths.
            output_dir: Output directory.

        Returns:
            ScriptResult from the run_macro call.
        """
        with open(script_path, "r", encoding="utf-8") as f:
            script_content = f.read()

        namespace: Dict[str, Any] = {}
        exec(script_content, namespace)

        if "run_macro" not in namespace:
            from image_splitter.script_engine import ScriptResult
            return ScriptResult(False, "Macro script has no run_macro() function")

        result = namespace["run_macro"](input_files, output_dir)
        return result

    @staticmethod
    def play_string(
        script_content: str,
        input_files: List[str],
        output_dir: str = "./output",
    ) -> Any:
        """Execute macro script content directly.

        Args:
            script_content: The macro script as a string.
            input_files: List of input image paths.
            output_dir: Output directory.

        Returns:
            ScriptResult from the run_macro call.
        """
        namespace: Dict[str, Any] = {}
        exec(script_content, namespace)

        if "run_macro" not in namespace:
            from image_splitter.script_engine import ScriptResult
            return ScriptResult(False, "Macro script has no run_macro() function")

        result = namespace["run_macro"](input_files, output_dir)
        return result
